# Code generated by fabricator-generate-project-go
#
# Modifications in code regions will be lost during regeneration!

# -----------------------------------------------------------------------------
# DEFINES
# -----------------------------------------------------------------------------

# Directory to compile binaries to
BINDIR                  ?= bin
# List of platforms to target [linux/windows/darwin]
PLATFORMS               ?= linux
# List of architectures to target [amd64/arm64]
ARCHITECTURES           := amd64
# Name of the app used for single application builds
APP 					:= 
# List of applications to build (must reside in ./cmd/<name>)
APPLICATIONS            := 
# Buildtime of a version will be passed as ldflag to go compiler
ifeq ($(OS),Windows_NT)
    VERSION_DATE := $(shell powershell -Command "Get-Date -Format o")
else
    VERSION_DATE := $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
endif
# Default version
svermakerBuildVersion   ?= unreleased
svermakerHelmLabel 	    ?= unreleased
goModuleBuildVersion    ?= unreleased
# GOPRIVATE will disable go cache
export GOPRIVATE        := code.cestus.io/*

# additional LDFGLAGS (e.g. -w -s)
ADDITIONALLDFLAGS       ?= 

ADDITIONAL_CI_STEPS ?= 