// Code generated by fabricator-generate-go
//
// Modifications in code regions will be lost during regeneration!
package wire

// region CODE_REGION(GEN)
//go:generate fabricator generate go
// endregion
