// Code generated by fabricator-generate-project-go
//
// Modifications in code regions will be lost during regeneration!
// region CODE_REGION(name)
module code.cestus.io/tools/wire

go 1.23

toolchain go1.24rc2

// endregion

require (
	github.com/google/go-cmp v0.6.0
	github.com/google/subcommands v1.2.0
	github.com/pmezard/go-difflib v1.0.0
	golang.org/x/tools v0.29.0
)

require (
	golang.org/x/mod v0.22.0 // indirect
	golang.org/x/sync v0.10.0 // indirect
)
