// Code generated by fabricator-generate-plugin-go
//
// Modifications in code regions will be lost during regeneration!

package wire

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"testing"
)

func TestFabricatorGenerateProjectGo(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "wire Suite")
}
